### ISSUE TITLE
大口事業所個別番号データのパース

### ISSUE THREAD

**Issue by iwate** [commerble/postal#1]
大口事業所個別番号データもパースしたい。

https://www.post.japanpost.jp/zipcode/dl/jigyosyo/readme.html

**Comment by takepara** [comment]
パースする機能追加しました。
Kenデータとの間で郵便番号が重複するものがあるけど、そこは別問題として対応考える必要がありそうです。

**Comment by iwate** [comment]
2入力にしてしまうと、Razorへ渡すモデルが1階層ネストしてしまいますから、
CSVのマージ（Distinct）は外で別ツールまたはシェルスクリプトで。

必要な時は別途チケットを切るということで。
